services:
  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userDB
    volumes:
      - micro-go-pg-data:/var/lib/postgresql/data

volumes:
  micro-go-pg-data:
