version: '3'

services: 
  broker-service: 
    image: maxmel/broker-service:1.0.0
    ports:
      - target: 80
        published: 8080
        mode: host
    deploy:
      mode: replicated 
      replicas: 1
  
  listener-service: 
    image: maxmel/listener-service:1.0.0
    deploy:
      mode: replicated 
      replicas: 1
  
  authentication-service: 
    image: maxmel/authentication-service:1.0.0
    deploy:
      mode: replicated 
      replicas: 1
    environment: 
      DSN: "host=postgres port=5432 user=postgres password=password dbname=userDB sslmode=disable timezone=UTC connect_timeout=5"

  logger-service:
    image: maxmel/logger-service:1.0.0
    deploy:
      mode: replicated 
      replicas: 1
  
  mail-service:
    image: maxmel/mail-service:1.0.0
    deploy:
      mode: replicated 
      replicas: 1
    environment:
      MAIL_PORT: 1025
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: none
      FROM_NAME: "John Smith"
      FROM_ADDRESS: "john.smith@example.com"
  
  # Third party
  postgres:
    image: 'postgres:14.2'
    ports:
      - target: 5432
        published: 5432
        mode: host
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userDB
    volumes:
      - micro-go-pg-data:/var/lib/postgresql/data
  
  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - target: 27017
        published: 27017
        mode: host
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - micro-go-mongo-data:/data/db
  
  mailhog:
    image: "jcalonso/mailhog:latest"
    ports:
      - target: 8025
        published: 8025
        mode: host
    deploy:
      mode: global
  
  rabbitmq:
    image: "rabbitmq:3.9-alpine"
    deploy: 
      mode: global
    volumes: 
      - micro-go-rabbitmq-data:/var/lib/rabbitmq/
        
volumes:
  micro-go-pg-data:
  micro-go-mongo-data:
  micro-go-rabbitmq-data: